//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleContractsConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISecondServiceContract")]
    public interface ISecondServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecondServiceContract/GetWhileAuthenticated", ReplyAction="http://tempuri.org/ISecondServiceContract/GetWhileAuthenticatedResponse")]
        string GetWhileAuthenticated();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecondServiceContract/GetWhileAuthenticated", ReplyAction="http://tempuri.org/ISecondServiceContract/GetWhileAuthenticatedResponse")]
        System.Threading.Tasks.Task<string> GetWhileAuthenticatedAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecondServiceContractChannel : MultipleContractsConsoleClient.ServiceReference1.ISecondServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecondServiceContractClient : System.ServiceModel.ClientBase<MultipleContractsConsoleClient.ServiceReference1.ISecondServiceContract>, MultipleContractsConsoleClient.ServiceReference1.ISecondServiceContract {
        
        public SecondServiceContractClient() {
        }
        
        public SecondServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecondServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecondServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecondServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWhileAuthenticated() {
            return base.Channel.GetWhileAuthenticated();
        }
        
        public System.Threading.Tasks.Task<string> GetWhileAuthenticatedAsync() {
            return base.Channel.GetWhileAuthenticatedAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFirstServiceContract")]
    public interface IFirstServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstServiceContract/GetWhileAnonymous", ReplyAction="http://tempuri.org/IFirstServiceContract/GetWhileAnonymousResponse")]
        string GetWhileAnonymous();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstServiceContract/GetWhileAnonymous", ReplyAction="http://tempuri.org/IFirstServiceContract/GetWhileAnonymousResponse")]
        System.Threading.Tasks.Task<string> GetWhileAnonymousAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirstServiceContractChannel : MultipleContractsConsoleClient.ServiceReference1.IFirstServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirstServiceContractClient : System.ServiceModel.ClientBase<MultipleContractsConsoleClient.ServiceReference1.IFirstServiceContract>, MultipleContractsConsoleClient.ServiceReference1.IFirstServiceContract {
        
        public FirstServiceContractClient() {
        }
        
        public FirstServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirstServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWhileAnonymous() {
            return base.Channel.GetWhileAnonymous();
        }
        
        public System.Threading.Tasks.Task<string> GetWhileAnonymousAsync() {
            return base.Channel.GetWhileAnonymousAsync();
        }
    }
}
